### ISSUE TITLE
Error in @ApiModelProperty

### ISSUE THREAD

**Issue by haroon407** [olivierlsc/example-swagger-express-ts#1]
Whenever I add the @ApiModelProperty on the attributes in my model I get the following error while building the code:

error: Cannot access property name on undefined
var propertyType = Reflect.getMetadata("design:type", target, propertyKey).name.toLowerCase();

Any idea why is this happening?

**Comment by olivierlsc** [comment]
This issue has a parent [#13](https://github.com/olivierlsc/swagger-express-ts/issues/13) in swagger-express-ts. I close this issue.

**Comment by nirajbisht** [comment]
@swagge in koa framework  Hello sir can i use this npm in my koa project
